query.order.search = {
  query: `query Q($search: searchInputObjectType){
    getOrderList(
      search: $search
    ){
      data{
        id
        userId
        orderNo
        userInfo{
          name
          email
          mobile
          tel
          memberGroupId
        }
        categories{
          products{
            productId
            variantId
            title{
              zh_TW
            }
            type
            sku
            vendorSku
            listPrice
            retailPrice
            totalPrice
            discountPrice
            quantity
            specs{
              specId
              title{
                zh_TW
              }
            }
            galleryInfo{
              mainId
              media
            }
            activityInfo{
              plugin
              title{
                zh_TW
              }
              discountPrice
            }
          }
        }
        paymentInfo{
          status
          price
          list{
            paymentId
            template
            name
            description
            price
            paymentTime
          }
        }
        shipmentInfo{
          status
          price
          list{
            shipmentId
            template
            name
            description
            price
            number
            shipmentTime
            recipient{
              email
              name
              mobile
              tel
              address{
                country
                postalCode
                streetAddress
              }
            }
          }
        }
        orderRegularId
        environment{
          userAgent{
            browserName
            browserVersion
            os
            deviceModel
            deviceType
          }
          domain
          locale
          currency
        }
        invoiceInfo{
          invoiceType
          invoiceTitle
          invoiceVAT
          donateUnit
          streetAddress
          vehicleType
          citizenDigitalCertificate
          mobileBarcode
        }
        activityInfo{
          plugin
          title{
            zh_TW
          }
        }
        priceInfo{
          currency
          cost
          discount
          total
          adjust
          orderDiscount
          productPrice
          productQuantity
          productDiscount
          shipmentFee
          shipmentDiscount
          return
          actualTotal
        }
        status
        note
        comment
        createdOn
        updatedOn
      }
      total
    }
  }`,
  variables:{
    search: {
      size: 10,
      from: 0,
      filter: {
        and: [
        ]
      },
      sort: [
        {
          field: 'createdOn',
          order: 'desc'
        }
      ]
    }
  }
};
