query.order.update = {
  query: `mutation M($search: [UpdateOrder]){
    updateOrderList(
      updateOrderList: $search
    ){
      id
      userId
      orderNo
      userInfo{
        name
        email
        mobile
        tel
        memberGroupId
      }
      categories{
        products{
          productId
          variantId
          title{
            zh_TW
          }
          type
          sku
          vendorSku
          listPrice
          retailPrice
          totalPrice
          discountPrice
          quantity
          specs{
            specId
            title{
              zh_TW
            }
          }
          galleryInfo{
            mainId
            media
          }
          activityInfo{
            plugin
            title{
              zh_TW
            }
            discountPrice
          }
        }
      }
      paymentInfo{
        status
        price
        list{
          paymentId
          template
          name
          description
          price
          paymentTime
        }
      }
      shipmentInfo{
        status
        price
        list{
          shipmentId
          template
          name
          description
          price
          number
          shipmentTime
          recipient{
            email
            name
            mobile
            tel
            address{
              country
              postalCode
              streetAddress
            }
          }
        }
      }
      orderRegularId
      environment{
        userAgent{
          browserName
          browserVersion
          os
          deviceModel
          deviceType
        }
        domain
        locale
        currency
      }
      invoiceInfo{
        invoiceType
        invoiceTitle
        invoiceVAT
        donateUnit
        streetAddress
        vehicleType
        citizenDigitalCertificate
        mobileBarcode
      }
      activityInfo{
        plugin
        title{
          zh_TW
        }
      }
      priceInfo{
        currency
        cost
        discount
        total
        adjust
        orderDiscount
        productPrice
        productQuantity
        productDiscount
        shipmentFee
        shipmentDiscount
        return
        actualTotal
      }
      status
      note
      comment
      createdOn
      updatedOn
      _error
    }
  }`,
  variables:{
    search: [
      {
        id: 'e72bba40-04af-11e7-9639-fd1c3ec64efb',
        shipmentInfo: {
          status: 2
        }
      }
    ]
  }
};
